### ISSUE TITLE
Broken TLS on seattlehaskell.org

### ISSUE THREAD

**Issue by d6e** [seahug/seahug.github.io#2]
Any way we can get https fixed for seattlehaskell.org?

**Comment by rcook** [comment]
"Enforce HTTPS" is currently disabled since this site uses a custom domain:

![custom-domain](https://user-images.githubusercontent.com/425396/37932206-bee098e2-30fc-11e8-81ab-1d2fe0e5a07e.png)

It sounds like GitHub might be gradually adding support for HTTPS for custom domains. I think we'll need to wait a wee while longer.

**Comment by d6e** [comment]
I've noticed Godaddy is used as the DNS service for seattlehaskell.org, any interest in using Cloudflare? It seems to be the common github pages workaround for TLS on custom domains. https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by rcook** [comment]
Yes, I am using GoDaddy for DNS. Ideally, GitHub will complete rolling out its proper fix, since the CloudFlare solution still allows MITM attacks between CloudFlare and GitHub. If I get some spare time I'll take a look at it again. Thanks!

**Comment by d6e** [comment]
👍

**Comment by rcook** [comment]
@d6e: Good news! GitHub have enabled SSL for custom domains for everyone now. I have configured seattlehaskell.org to enforce SSL now. Thanks!
